version: '3.4'

volumes:
  datausers:

services:
  dbusuarios:
    image: mysql:8.0.22
    ports:
      - "3308:3306"
    volumes:
      - datausers:/var/lib/mysql
      - "~/sql-scripts/setup.sql:/docker-entrypoint-initdb.d/1.sql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: usuariodb
    networks:
      - usersrede

  usuariosapi:
    build:
      context: ./UserApi/UserApi
      dockerfile: Dockerfile
    depends_on:
      - dbusuarios
    ports:
      - "8080:80"
    restart: always
    environment: 
      - DBHOST=dbusuarios
    networks:
      - usersrede

  coraisfront:
    build:
      context: ./coraisfront
      dockerfile: Dockerfile
    depends_on:
      - usuariosapi
    ports:
      - "4200:4200"
    restart: always
    networks:
      - usersrede

networks:
  usersrede:
    driver:
      bridge